name: Workflow Cleanup

on:
  schedule:
    # 每月1号 UTC 时间 0 点运行（北京时间 8 点）
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write  # 必须要有写入权限才能删除运行记录
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cleanup workflow runs (Skip Pending)
      uses: jv-k/delete-workflow-runs@main
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        keep-successful: 2    # 保留最近2次成功运行
        keep-failed: 1        # 保留最近1次失败运行
        skip-pending: true    # 跳过未完成的运行（不删除 pending/running 状态）
        dry-run: false        # 设为 true 可先测试不实际删除
