name: Cleanup workflow runs and artifacts

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: '0 8/12 * * *'  # 每12小时在整点运行一次（UTC时间）

env:
  KEEP_SUCCESSFUL_RUNS: 2    # 保留最近2次成功运行
  KEEP_FAILED_RUNS: 1        # 保留最近1次失败运行

jobs:
  cleanup:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cleanup workflow runs
      uses: c-hive/gha-remove-workflow-runs@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        keep-successful: ${{ env.KEEP_SUCCESSFUL_RUNS }}
        keep-failed: ${{ env.KEEP_FAILED_RUNS }}
        keep-pending: 0       # 不保留pending状态的运行
        keep-abandoned: 0     # 不保留abandoned状态的运行
        dry-run: false       # 设为true可先测试不实际删除
