name: up_fork
on:
  workflow_dispatch:
 # schedule:
 #   - cron: 0 */8 * * *   
  
jobs:
 lede:
    runs-on: ubuntu-latest
    steps:
      - uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          upstream_repository: coolsnowwolf/lede
          target_repository: MXJNZ6/lede
          upstream_branch: master
          target_branch: master
          force: true
          tags: true

 freenom-py:
    runs-on: ubuntu-latest
    steps:
      - uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          upstream_repository: Oreomeow/freenom-py
          target_repository: MXJNZ6/freenom-py
          upstream_branch: main
          target_branch: main
          force: true
          tags: true
          
 freenom:
    runs-on: ubuntu-latest
    steps:
      - uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          upstream_repository: luolongfei/freenom
          target_repository: MXJNZ6/freenom
          upstream_branch: main
          target_branch: main
          force: true
          tags: true
          
 reader:
    runs-on: ubuntu-latest
    steps:
      - uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          upstream_repository: hectorqin/reader
          target_repository: MXJNZ6/reader
          upstream_branch: master
          target_branch: master
          force: true
          tags: true

 ax1800:
    runs-on: ubuntu-latest
    steps:
      - uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          upstream_repository: coolsnowwolf/openwrt-gl-ax1800
          target_repository: MXJNZ6/openwrt-gl-ax1800
          upstream_branch: master
          target_branch: master
          force: true
          tags: true

 sub-web:
    runs-on: ubuntu-latest
    steps:
      - uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          upstream_repository: CareyWang/sub-web
          target_repository: MXJNZ6/sub-web
          upstream_branch: master
          target_branch: master
          force: true
          tags: true

 techxuexi-js:
    runs-on: ubuntu-latest
    steps:
      - uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          upstream_repository: TechXueXi/techxuexi-js
          target_repository: MXJNZ6/techxuexi-js
          upstream_branch: main
          target_branch: main
          force: true
          tags: true

 over:
    needs: [lede,freenom-py,freenom,reader,ax1800,sub-web,techxuexi-js]
    runs-on: ubuntu-latest
    steps:

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 0
        keep_minimum_runs: 0
