name: OpenWrt Config Builder

on:
  workflow_dispatch:
    inputs:
      enable_ssh:
        description: 'Enable SSH debugging (true/false)'
        required: false
        default: 'false'

env:
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  REPO_BRANCH: master
  CONFIG_FILE: X86_imm.config
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up build environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android
        sudo apt-get update
        sudo apt-get -y install \
          build-essential ccache flex gawk gettext git libncurses5-dev libssl-dev \
          python3 python3-distutils rsync unzip zlib1g-dev file wget
        sudo timedatectl set-timezone "$TZ"

    - name: Clone source code
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Start tmate session (if enabled)
      if: inputs.enable_ssh == 'true'
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true
        connect-timeout-seconds: 1800  # 30 minutes timeout

    - name: Generate config
      id: config
      run: |
        cd openwrt
        [ -f "../$CONFIG_FILE" ] && cp "../$CONFIG_FILE" .config || make defconfig
        echo "CONFIG_PATH=$(pwd)/.config" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Upload config
      uses: actions/upload-artifact@v4
      if: steps.config.outputs.status == 'success'
      with:
        name: openwrt-config
        path: ${{ env.CONFIG_PATH }}
        retention-days: 3
